name: Zeitgeist
favicon: null
layout_spectrum: 0.7977112897206098
typography_spectrum: 0.42110134614631534
title: Spirit of the age
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#12864a'
    - '#66b473'
    - '#52534d'
  brandStrength: 0.9242798078339547
  lightness: 0.314628777327016
  saturation: 0.32673438475467265
  rhythmicContrast: 0.26405545324087143
purpose: []
